from collections.abc import Sequence
from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.domain.entities import (
    Asset,
    Audit,
    AuditDraft,
    Brand,
    BrandBook,
    BrandBrief,
    Chunk,
    GeneratedCopy,
    User,
)
from app.domain.enums import AssetKind, AssetStatus, Role


class UserRepository(Protocol):
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def add(self, *, email: str, name: str, role: Role, hashed_password: str) -> User: ...
    async def get_password_hash(self, email: str) -> str | None: ...


class RefreshTokenRepository(Protocol):
    async def add(self, *, user_id: UUID, token_hash: str, expires_at: datetime) -> None: ...
    async def get_user_id(self, token_hash: str) -> UUID | None: ...
    async def revoke(self, token_hash: str) -> None: ...
    async def revoke_all(self, user_id: UUID) -> None: ...


class BrandRepository(Protocol):
    async def get_current(self) -> Brand | None: ...
    async def get(self, brand_id: UUID) -> Brand | None: ...
    async def save(self, brand: Brand) -> Brand: ...
    async def replace_chunks(self, brand_id: UUID, chunks: Sequence[Chunk]) -> None: ...
    async def list_chunks(self, brand_id: UUID) -> list[Chunk]: ...
    async def search_chunks(self, brand_id: UUID, query: str, k: int = 4) -> list[Chunk]: ...


class AssetRepository(Protocol):
    async def add(self, asset: Asset) -> Asset: ...
    async def get(self, asset_id: UUID) -> Asset | None: ...
    async def list(self, *, status: AssetStatus | None = None) -> list[Asset]: ...
    async def set_status(self, asset_id: UUID, status: AssetStatus) -> Asset: ...


class AuditRepository(Protocol):
    async def add(self, audit: Audit) -> Audit: ...


class BrandComposer(Protocol):
    async def compose(self, brief: BrandBrief) -> BrandBook: ...


class CopyGenerator(Protocol):
    async def generate(
        self,
        *,
        kind: AssetKind,
        brand: Brand,
        context: Sequence[Chunk],
        prompt: str,
    ) -> GeneratedCopy: ...


class VisionAuditor(Protocol):
    async def audit(self, *, brand: Brand, image_name: str, image: bytes) -> AuditDraft: ...


class UnitOfWork(Protocol):
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
